---
name: Test OIDC Debugger
on:
  workflow_dispatch:
jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: secure
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: run oidc-debug.go
        run: go run cmd/oidc-debug.go -audience "https://iam.googleapis.com/projects/..."
